### ISSUE TITLE
stakholder on unconfirmed chain limit

### ISSUE THREAD

**Issue by monsterbitar** [SoftwareVerde/bitcoin-cash-chips#4]
I would like to have wallet makers listed as a specific stakeholder group as one of their primary tasks is to create valid transactions. They are not the most likely user group to encounted the issue (due to peoples spending habits), but they do have to take this into consideration today.

I am such a wallet maker (https://gitlab.com/monsterbitar/cashual-wallet), altough I haven't gotten my wallet out of beta yet, and offer the following statement on this matter:

> I believe that for money to be useful, it needs to be able to move at low cost and with ease. The current unconfirmed transaction chain limitation is effectively friction that makes Bitcoin Cash less useful as money, and I support a complete removal of the limit.

**Comment by SugarFrostedSugarPuff** [comment]
Thanks, Jonathan! I believe we agree wallet makers should be listed in the stakeholders group and I will be adding your statement to my next edit.  Thank you for offering a direct statement as well.

**Comment by joshmg** [comment]
This was resolved as a part of PR #6 .  Thanks for the feedback, Jonathan.
